# pull the official base image
FROM node:16-alpine
# set working direction
WORKDIR /usr/src/app
# add `/app/node_modules/.bin` to $PATH
ENV PATH usr/src/app/node_modules/.bin:$PATH
# install application dependencies
COPY package.json ./
#COPY package-lock.json ./
RUN npm install
CMD ["npm", "run", "start-dev"]