version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    environment:
      - NODE_ENV=docker_compose
      - PORT=8080
      - API_KEY=swordfish
      - BASE_URL=/api/v1/
    ports:
      - 8080:8080
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - postgres
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    environment:
      - PORT=3000
      - REACT_APP_API_URL=api/v1
      - REACT_APP_API_KEY=swordfish
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=knex
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=knex
    ports:
      - 5433:5432
