apiVersion: v1
kind: ConfigMap
metadata:
  name: dotenv
  namespace: project
data:  
  POSTGRES_DB: "postgres"
  POSTGRES_PASSWORD: "swordfish"
  POSTGRES_USER: "admin"
  POSTGRES_HOST: "postgres-service"
  API_KEY: "swordfish"