apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: sumdrill # This is the app as declared in the deployment.
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 8080
